INSERT INTO `perfil` VALUES ('1', null, 'alimentação');
INSERT INTO `perfil` VALUES ('2', null, 'supermercados');
INSERT INTO `perfil` VALUES ('3', null, 'padarias / bistros / cafés');
INSERT INTO `perfil` VALUES ('4', null, 'moda / fantasias');
INSERT INTO `perfil` VALUES ('5', 'Academia / Pilates / Clínicas', 'saúde');
INSERT INTO `perfil` VALUES ('6', 'Passeios / Parques', 'lazer');
INSERT INTO `perfil` VALUES ('7', null, 'festas / eventos / shows / dan');
INSERT INTO `perfil` VALUES ('8', null, 'bares');
INSERT INTO `perfil` VALUES ('9', 'Livrarias / Cinemas / Teatro', 'cultural');
INSERT INTO `perfil` VALUES ('10', 'Pontos Turísticos / Hístóricos da Cidade', 'histórico');
INSERT INTO `perfil` VALUES ('11', '\"Pague hoje seu IPVA com 30% de desconto\"', 'Informativo');
INSERT INTO `perfil` VALUES ('12', null, 'eletroeletrônicos');
INSERT INTO `perfil` VALUES ('13', null, 'esportes');
INSERT INTO `perfil` VALUES ('14', null, 'eróticos');
INSERT INTO `perfil` VALUES ('15', null, 'casa e construção');
INSERT INTO `perfil` VALUES ('16', 'Spa / Salão de Beleza', 'beleza');
INSERT INTO `perfil` VALUES ('17', null, 'farmácias / drogarias');
INSERT INTO `perfil` VALUES ('18', null, 'pousadas / hotéis / Motéis');
INSERT INTO `perfil` VALUES ('19', 'Escolas de Idioma / Cursos de Extensão', 'acadêmico');
INSERT INTO `perfil` VALUES ('20', null, 'imobiliárias');
INSERT INTO `perfil` VALUES ('21', null, 'petShops');
INSERT INTO `perfil` VALUES ('22', null, 'camping / pesca');
INSERT INTO `perfil` VALUES ('23', null, 'concessionárias');
INSERT INTO `perfil` VALUES ('24', null, 'bancos');
INSERT INTO `perfil` VALUES ('25', null, 'brinquedos');
INSERT INTO `perfil` VALUES ('26', 'Instrumentos / CD\'s / Aulas de Instrumentos / Danças', 'musical');
INSERT INTO `perfil` VALUES ('27', null, 'perfumaria / cosméticos');
INSERT INTO `perfil` VALUES ('28', null, 'empregos / concursos');
INSERT INTO `perfil` VALUES ('29', 'Manutenção / Encanador / Pedreiro / Detetização', 'serviços');