INSERT INTO `perfil` VALUES ('1', 'alimentação');
INSERT INTO `perfil` VALUES ('2', 'supermercados');
INSERT INTO `perfil` VALUES ('3', 'padarias / bistros / cafés');
INSERT INTO `perfil` VALUES ('4', 'moda / fantasias');
INSERT INTO `perfil` VALUES ('5', 'saúde');
INSERT INTO `perfil` VALUES ('6', 'lazer');
INSERT INTO `perfil` VALUES ('7', 'festas / eventos / shows / dan');
INSERT INTO `perfil` VALUES ('8', 'bares');
INSERT INTO `perfil` VALUES ('9', 'cultural');
INSERT INTO `perfil` VALUES ('10', 'histórico');
INSERT INTO `perfil` VALUES ('11', 'Informativo');
INSERT INTO `perfil` VALUES ('12', 'eletroeletrônicos');
INSERT INTO `perfil` VALUES ('13', 'esportes');
INSERT INTO `perfil` VALUES ('14', 'eróticos');
INSERT INTO `perfil` VALUES ('15', 'casa e construção');
INSERT INTO `perfil` VALUES ('16', 'beleza');
INSERT INTO `perfil` VALUES ('17', 'farmácias / drogarias');
INSERT INTO `perfil` VALUES ('18', 'pousadas / hotéis / Motéis');
INSERT INTO `perfil` VALUES ('19', 'acadêmico');
INSERT INTO `perfil` VALUES ('20', 'imobiliárias');
INSERT INTO `perfil` VALUES ('21', 'petShops');
INSERT INTO `perfil` VALUES ('22', 'camping / pesca');
INSERT INTO `perfil` VALUES ('23', 'concessionárias');
INSERT INTO `perfil` VALUES ('24', 'bancos');
INSERT INTO `perfil` VALUES ('25', 'brinquedos');
INSERT INTO `perfil` VALUES ('26', 'musical');
INSERT INTO `perfil` VALUES ('27', 'perfumaria / cosméticos');
INSERT INTO `perfil` VALUES ('28', 'empregos / concursos');
INSERT INTO `perfil` VALUES ('29', 'serviços');