INSERT INTO `sub_perfil` VALUES ('1', '5', 'Academia');
INSERT INTO `sub_perfil` VALUES ('2', '5', 'Pilates');
INSERT INTO `sub_perfil` VALUES ('3', '5', 'Clínicas');
INSERT INTO `sub_perfil` VALUES ('4', '6', 'Passeios');
INSERT INTO `sub_perfil` VALUES ('5', '6', 'Parques');
INSERT INTO `sub_perfil` VALUES ('6', '9', 'Livrarias');
INSERT INTO `sub_perfil` VALUES ('7', '9', 'Cinemas');
INSERT INTO `sub_perfil` VALUES ('8', '9', 'Teatro');
INSERT INTO `sub_perfil` VALUES ('9', '10', 'Pontos Turísticos');
INSERT INTO `sub_perfil` VALUES ('10', '10', 'Históricos da Cidade');
INSERT INTO `sub_perfil` VALUES ('11', '11', 'Pague hoje seu IPVA com 30% de desconto');
INSERT INTO `sub_perfil` VALUES ('12', '16', 'SPA');
INSERT INTO `sub_perfil` VALUES ('13', '16', 'Salão de Beleza');
INSERT INTO `sub_perfil` VALUES ('14', '19', 'Escolas de Idiomas');
INSERT INTO `sub_perfil` VALUES ('15', '19', 'Cursos de Extensão');
INSERT INTO `sub_perfil` VALUES ('16', '26', 'Instrumentos');
INSERT INTO `sub_perfil` VALUES ('17', '26', 'CD\'s');
INSERT INTO `sub_perfil` VALUES ('18', '26', 'Aulas de Instrumentos');
INSERT INTO `sub_perfil` VALUES ('19', '26', 'Danças');
INSERT INTO `sub_perfil` VALUES ('20', '29', 'Manutenção');
INSERT INTO `sub_perfil` VALUES ('21', '29', 'Encanador');
INSERT INTO `sub_perfil` VALUES ('22', '29', 'Pedreiro');
INSERT INTO `sub_perfil` VALUES ('23', '29', 'Detetização');